#!/bin/bash

script_dir="$(dirname "$0")/scripts"

source "${script_dir}/styles.sh"

if [[ -z "${plum_repo}" ]]; then
    plum_repo='rime/plum'
fi

if [[ -z "${rime_dir}" ]]; then
    # Output to default Rime user directory
    case "$OSTYPE" in
        darwin*)
            # Squirrel
            rime_dir="$HOME/Library/Rime"
            ;;
        linux*)
            # ibus-rime
            rime_dir="$HOME/.config/ibus/rime"
            ;;
        cygwin* | msys* | win*)
            # Weasel
            rime_dir="$APPDATA\\Rime"
            ;;
        *)
            rime_dir='.'
            ;;
    esac
fi

if [[ -z "${plum_dir}" ]]; then
    # am I in a working copy already?
    plum_dir="$(dirname "$0")"
    if ! [[ -d "${plum_dir}/scripts" ]]; then
        # make a copy of plum in a subdirectory
        plum_dir='plum'
    fi
fi

if ! [[ -e "${plum_dir}" ]]; then
    git clone --depth 1 "https://github.com/${plum_repo}.git" "${plum_dir}"
fi

if [[ $# -eq 0 ]]; then
    targets=(':preset')
else
    targets=$@
fi

for target in ${targets[@]}; do
    if [[ "${target}" == 'self-update' ]]; then
        echo $(result "Updating plum at") "'${plum_dir}'"
        (cd "${plum_dir}"; git pull)
        continue
    fi

    bash "${plum_dir}"/scripts/install-packages.sh "${target}" "${rime_dir}"
done
